"""Render a local video replay from actual benchmark outputs. Contains confidential data."""
import argparse
import json
import subprocess
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont
import imageio_ffmpeg


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    repo = Path(__file__).resolve().parents[1]
    if args.output.resolve().is_relative_to(repo) or args.results_dir.resolve().is_relative_to(repo):
        parser.error("Keep confidential inputs and videos outside the repository.")
    samples = json.loads((args.results_dir / "samples.json").read_text())
    outputs = {b: json.loads((args.results_dir / f"{b}-results.json").read_text())
               for b in ["paddle", "florence"]}
    frames_dir = args.results_dir / "video-frames"
    frames_dir.mkdir(exist_ok=True)
    fonts = Path("C:/Windows/Fonts")
    def font(size, bold=False):
        return ImageFont.truetype(str(fonts / ("arialbd.ttf" if bold else "arial.ttf")), size)
    small, body, title = font(20), font(24), font(38, True)
    def frame(heading, subheading):
        im = Image.new("RGB", (1280, 720), "#111827")
        d = ImageDraw.Draw(im)
        d.text((44, 30), heading, font=title, fill="#ffffff")
        d.text((44, 90), subheading, font=small, fill="#a5b4fc")
        d.text((44, 680), "LOCAL ONLY | Confidential challenge data | Replay of actual benchmark outputs",
               font=small, fill="#9ca3af")
        return im, d
    def paragraph(d, text, x, y, width, max_lines=7, f=body):
        words = text.replace("\n", " ").split()
        lines, line = [], ""
        for word in words:
            candidate = (line + " " + word).strip()
            if d.textlength(candidate, font=f) <= width:
                line = candidate
            else:
                if line:
                    lines.append(line)
                line = word
        if line:
            lines.append(line)
        if len(lines) > max_lines:
            raise ValueError("Model transcript does not fit video panel; increase its layout.")
        for i, line in enumerate(lines):
            d.text((x, y + i * 32), line, font=f, fill="#e5e7eb")
    scenes = []
    im, d = frame("How the ML models read a drawing", "EspCa3B | Page 37 | Three identical image crops | CPU inference")
    paragraph(d, "1. Render the PDF locally and select a high-resolution crop.", 60, 175, 1150)
    paragraph(d, "2. Give that image to each pretrained ML model.", 60, 245, 1150)
    paragraph(d, "3. Read the text generated by the model and parse reinforcement candidates.", 60, 315, 1150)
    paragraph(d, "4. Compare the extracted candidates against native PDF text.", 60, 385, 1150)
    paragraph(d, "This video shows saved inference outputs. It does not visualize the models' internal attention.", 60, 485, 1150)
    target = frames_dir / "intro.png"; im.save(target); scenes.append((target, 8))
    for index, sample in enumerate(samples):
        im, d = frame(f"Sample {index + 1}: drawing image to recognized text",
                      "Both models received this image. Native PDF text was used only for comparison afterwards.")
        crop = Image.open(sample["file"]).convert("RGB")
        crop.thumbnail((850, 250))
        im.paste(crop, ((1280 - crop.width) // 2, 130))
        for backend, x, label in [("paddle", 44, "PaddleOCR PP-OCRv5 mobile"),
                                  ("florence", 664, "Florence-2 base")]:
            r = outputs[backend]["results"][index]
            d.rounded_rectangle((x, 395, x + 572, 650), radius=12, fill="#1f2937")
            d.text((x + 18, 410), label, font=font(23, True), fill="#93c5fd")
            d.text((x + 18, 445), f"Measured inference: {r['seconds']:.2f} seconds", font=small, fill="#86efac")
            paragraph(d, r["text"], x + 18, 487, 536, max_lines=5, f=small)
        target = frames_dir / f"sample-{index + 1}.png"
        im.save(target); scenes.append((target, 16))
    im, d = frame("What this experiment demonstrated", "Agreement with native PDF text on three selected crops")
    paragraph(d, "PaddleOCR: 7/7 bar designations; 4/4 quantity-bar pairs; 4.0 seconds per crop.", 60, 175, 1150)
    paragraph(d, "Florence-2: 7/7 bar designations; 4/4 quantity-bar pairs; 14.1 seconds per crop.", 60, 275, 1150)
    paragraph(d, "Qwen was not run: insufficient available memory for the proposed configuration.", 60, 375, 1150)
    paragraph(d, "Next validation: manually checked annotations, spacing and lengths, then element matching. These results are not a verified accuracy score.", 60, 475, 1150)
    target = frames_dir / "summary.png"; im.save(target); scenes.append((target, 10))
    concat = frames_dir / "scenes.txt"
    content = "".join(f"file '{p.resolve().as_posix()}'\nduration {duration}\n" for p, duration in scenes)
    content += f"file '{scenes[-1][0].resolve().as_posix()}'\n"
    concat.write_text(content, encoding="utf-8")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    command = [imageio_ffmpeg.get_ffmpeg_exe(), "-y", "-hide_banner", "-loglevel", "error",
               "-f", "concat", "-safe", "0", "-i", str(concat), "-t", str(sum(t for _, t in scenes)),
               "-vf", "fps=24,format=yuv420p", "-c:v", "libx264", "-preset", "fast", "-crf", "20",
               "-movflags", "+faststart", str(args.output)]
    subprocess.run(command, check=True)
    print(json.dumps({"seconds": sum(t for _, t in scenes), "width": 1280, "height": 720,
                      "bytes": args.output.stat().st_size, "scenes": len(scenes)}))


if __name__ == "__main__":
    main()
